package com.bigproject.backend.domain.academicoperations.infrastructure;

import com.bigproject.backend.domain.academicoperations.application.CohortService;
import com.bigproject.backend.domain.academicoperations.domain.Cohort;
import com.bigproject.backend.domain.academicoperations.domain.AcademicOperationsErrorCode;
import com.bigproject.backend.domain.academicoperations.presentation.dto.CohortResponse;
import com.bigproject.backend.global.exception.ApiException;
import com.bigproject.backend.global.handle.ResourceResolver;
import com.bigproject.backend.global.security.CurrentUserResolver;
import tools.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import org.springframework.security.core.Authentication;
import org.springframework.stereotype.Component;

import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

/**
 * Hand-written, NOT auto-generated by {@code bskel handles emit} -- D-security-8 correctly
 * refused ({@link CohortService#findCohort} takes 2 arguments, {@code cohortId} and {@code orgId},
 * not the 1 the generated resolver always passes). Reading the real
 * {@code CohortController.findCohort} explained why: {@code GET /cohorts/{cohortId}} has NO role
 * check at all -- it is scoped by the caller's own organization, read from the access token
 * ({@code extractOrganizationId}), not a {@code hasRole(...)} check. This is exactly the
 * tenant-scoping shape {@link ResourceResolver#fetch}'s own javadoc names as the reason it now
 * receives {@code Authentication} at all (D-resolver-authentication-context). See DECISIONS.md
 * D-handles-pilot-cohort for the full pilot record.
 *
 * <p>{@code organizationId} is derived exactly the way {@code CohortController} itself does
 * ({@code authentication.getDetails()} cast to {@code UUID}) -- a handle-mediated fetch/patch is
 * scoped to the SAME organization the real endpoint would scope it to. A generated resolver could
 * not express this without silently dropping tenant isolation; that is the entire reason this file
 * is hand-written rather than templated.
 */
@Component
@RequiredArgsConstructor
public class CohortResolver implements ResourceResolver {

	private final CohortService cohortService;
	private final CurrentUserResolver currentUserResolver;
	private final ObjectMapper objectMapper;

	@Override
	public String type() {
		return CohortResolverPolicy.type();
	}

	@Override
	public Object fetch(UUID resourceUid, Authentication authentication) {
		UUID organizationId = extractOrganizationId(authentication);
		Cohort cohort = cohortService.findCohort(resourceUid, organizationId);
		List<UUID> ids = List.of(resourceUid);
		int traineeCount = cohortService.countActiveTrainees(ids, organizationId).getOrDefault(resourceUid, 0);
		int classroomCount = cohortService.countClassrooms(ids, organizationId).getOrDefault(resourceUid, 0);
		return CohortResponse.from(cohort, traineeCount, classroomCount);
	}

	/**
	 * Hand-written per-field dispatch, not the usual generated {@code (resourceUid, dtoPatch)}
	 * shape ({@code renderPatchFieldBody}'s own codegen assumes the real update service method
	 * takes {@code (resourceUid, dto)} -- {@link CohortService#updateCohort} takes
	 * {@code (cohortId, orgId, name, startDate, endDate, actorUserId)} instead, a real, different
	 * shape found while writing this, not a codegen limitation to work around blindly). All three
	 * fields of {@code UpdateCohortRequest} are the same null-means-unchanged convention
	 * (D-patch-strategy) the codegen path already recognizes -- {@code updateCohort} itself treats
	 * an omitted field as "leave unchanged", so passing {@code null} for the other two here is
	 * correct, not a shortcut.
	 */
	@Override
	public void patchField(UUID resourceUid, String pointer, Object value, Authentication authentication) {
		UUID organizationId = extractOrganizationId(authentication);
		UUID actorUserId = currentUserResolver.resolveCurrentMemberId();
		switch (pointer) {
			case "/name" -> {
				String name = objectMapper.convertValue(value, String.class);
				cohortService.updateCohort(resourceUid, organizationId, name, null, null, actorUserId);
			}
			case "/startDate" -> {
				LocalDate startDate = objectMapper.convertValue(value, LocalDate.class);
				cohortService.updateCohort(resourceUid, organizationId, null, startDate, null, actorUserId);
			}
			case "/endDate" -> {
				LocalDate endDate = objectMapper.convertValue(value, LocalDate.class);
				cohortService.updateCohort(resourceUid, organizationId, null, null, endDate, actorUserId);
			}
			default -> throw new UnsupportedOperationException(
					"patchField not implemented for Cohort" + pointer + " -- see this class's javadoc");
		}
	}

	@Override
	public String requiredAuthority() {
		return CohortResolverPolicy.requiredAuthority();
	}

	@Override
	public String requiredAuthorityForPatch() {
		return CohortResolverPolicy.requiredAuthorityForPatch();
	}

	@Override
	public String contractRef() {
		return CohortResolverPolicy.contractRef();
	}

	@Override
	public UUID featureUid() {
		return CohortResolverPolicy.featureUid();
	}

	// Mirrors CohortController's own private extractOrganizationId exactly -- same source, same
	// fail-closed behavior (ORGANIZATION_CONTEXT_MISSING) if the JWT's own org claim is absent.
	private UUID extractOrganizationId(Authentication authentication) {
		Object details = authentication.getDetails();
		if (!(details instanceof UUID organizationId)) {
			throw new ApiException(AcademicOperationsErrorCode.ORGANIZATION_CONTEXT_MISSING);
		}
		return organizationId;
	}
}
